# File: config.yaml
apiVersion: monitoring.googleapis.com/v1beta
kind: RunMonitoring
metadata:
  name: gemma-vllm-monitor
spec:
  endpoints:
  - port: 8000
    path: /metrics
    interval: 15s
    metricRelabeling:
    - action: replace
      sourceLabels:
      - __address__
      targetLabel: label_key
      replacement: label_value
  targetLabels:
    metadata:
    - service
    - revision